### ISSUE TITLE
Data Question

### ISSUE THREAD

**Issue by JTT94** [vsomnath/aligned_diffusion_bridges#1]
Thanks for making the code and data available!

Is it correct that the data here in https://github.com/vsomnath/aligned_diffusion_bridges/tree/main/reproducibility/statephate is the state-fate data from Weinreb 2018?

Do you have the original data source / link and are you aware of the license?

[1] https://www.biorxiv.org/content/10.1101/467886v2.full.pdf?

**Comment by vsomnath** [comment]
Hi James, thanks for reaching out! 

Yes, the data is from the same paper -- we looked at the published version of the article for the GEO accession numbers. (https://www.science.org/doi/10.1126/science.aaw3381#acknowledgments). 

They have a github link but it has no LICENSE, so we stuck to the normal GEO terms (https://catalog.data.gov/dataset/gene-expression-omnibus-geo). 

Tagging @matteopariset here incase I missed anything!
